# Generated by Django 3.1.7 on 2021-04-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feauture',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
    ]
