# Generated by Django 3.1.7 on 2021-04-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_product_feauture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feauture',
            field=models.BooleanField(default=True),
        ),
    ]
